/** Generated by scripts/prepare-performance-assets.mjs. */
export const imageDimensions: Record<string, { width: number; height: number }> = {
  "/assets/cats/bars.jpg": {
    "width": 1400,
    "height": 1050
  },
  "/assets/cats/dispensing.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/cats/koelers.jpg": {
    "width": 1400,
    "height": 1400
  },
  "/assets/cats/roermotoren.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/cats/serpentijnen.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/cats/service.jpg": {
    "width": 1400,
    "height": 1050
  },
  "/assets/products-catalog/aansluiting-pompuitgang.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/afvoerslang.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/ball-lock-gas.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/ball-lock-vloeistof.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/bandeja-1-met-mojacopas.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/bandeja-1-zonder-mojacopas.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/bandeja-2-met-mojacopas.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/bandeja-2-zonder-mojacopas.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/bandeja-3-met-mojacopas.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/bandeja-3-zonder-mojacopas.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/bandeja-4-plus.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/barrilero-doble.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/bedieningspaneel.jpg": {
    "width": 640,
    "height": 480
  },
  "/assets/products-catalog/bevestigingsklemmen.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/bierleiding.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/bocht-retourkoeling.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/buisuiteinden.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/cuba-caliente.jpg": {
    "width": 480,
    "height": 640
  },
  "/assets/products-catalog/cuba-frio.jpg": {
    "width": 480,
    "height": 640
  },
  "/assets/products-catalog/filter-ceramisch-32s.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/filter-moleculair-20g.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/flenzen.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/g8-agua-aire.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/g8-agua.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/g8-aire.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/g92-sin.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/g98-con.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/g98-sin.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/glycol.jpg": {
    "width": 1408,
    "height": 1408
  },
  "/assets/products-catalog/gold-ice.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/h50.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/irrigatieslang-contact.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/irrigatieslang-overstroming.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/isolatieslang.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/koppeling-key-keg.jpg": {
    "width": 600,
    "height": 443
  },
  "/assets/products-catalog/koppeling-type-a.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/koppeling-type-g.jpg": {
    "width": 600,
    "height": 470
  },
  "/assets/products-catalog/koppeling-type-s.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/kraanstaart-45.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/kranen-rvs.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/kranen-water-rvs.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/manorreductor-1.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/manorreductor-2.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/manorreductor-3.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/manorreductor-4.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/medaillon-tapzuil.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/mojacopas.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/neopreen-isolatieplaat.jpg": {
    "width": 1408,
    "height": 1408
  },
  "/assets/products-catalog/picky.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/pootdoppen.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/project-op-maat.jpg": {
    "width": 2025,
    "height": 1389
  },
  "/assets/products-catalog/pvc-cristal-slang.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/reinigingstanks.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/reinigingsvloeistof-serpentijn.jpg": {
    "width": 1408,
    "height": 1408
  },
  "/assets/products-catalog/relais-compressor.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/reparatie-koelers.jpg": {
    "width": 600,
    "height": 433
  },
  "/assets/products-catalog/reparatie-kranen.jpg": {
    "width": 600,
    "height": 433
  },
  "/assets/products-catalog/reparatie-roermotoren.jpg": {
    "width": 600,
    "height": 432
  },
  "/assets/products-catalog/rubberdoppen-overstroming.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/serpentijnen-bier-alcoholvrij.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/serpentijnen-bier-helicoidal.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/serpentijnen-bier.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/serpentijnen-cider.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/serpentijnen-op-maat.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/serpentijnen-sangria-frisdrank.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/serpentijnen-water.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/sin-bomba.jpg": {
    "width": 768,
    "height": 577
  },
  "/assets/products-catalog/snelkoppelingen.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/sonde-digitaal.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/startcondensator-compressor.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/startcondensator-roermotor.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/steun-lekbak.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/tapzuil-boa.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/tapzuil-circulair-dubbel.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/tapzuil-circulair.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/tapzuilen-afwerkingen.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/thermostaat-digitaal.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/thermostaat-elektronisch.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/thermostaat-mechanisch.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/unidad-condensadora.jpg": {
    "width": 960,
    "height": 721
  },
  "/assets/products-catalog/v200-portable.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/v300.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/v500.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/v90.jpg": {
    "width": 650,
    "height": 650
  },
  "/assets/products-catalog/ventilator.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/versterkte-co2-slang.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/wielen.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/y-stuk-co2.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-catalog/y-stuk-water.jpg": {
    "width": 600,
    "height": 600
  },
  "/assets/products-official/goldy.jpg": {
    "width": 1400,
    "height": 1400
  },
  "/assets/products-official/v100-portable.jpg": {
    "width": 1400,
    "height": 1400
  },
  "/assets/products-official/v100.jpg": {
    "width": 1400,
    "height": 1400
  },
  "/assets/products-official/v200.jpg": {
    "width": 1400,
    "height": 1400
  },
  "/assets/products-stage/cooler-extra-2.jpg": {
    "width": 1200,
    "height": 1200
  },
  "/worlds/ice-bank.jpg": {
    "width": 1792,
    "height": 907
  },
  "/worlds/original-dark/world-bar.jpg": {
    "width": 1792,
    "height": 907
  },
  "/worlds/original-dark/world-event.jpg": {
    "width": 1792,
    "height": 907
  },
  "/worlds/original-dark/world-install.jpg": {
    "width": 1792,
    "height": 907
  },
  "/worlds/statement-tap.jpg": {
    "width": 1600,
    "height": 1068
  },
  "/worlds/world-bar.jpg": {
    "width": 1792,
    "height": 907
  },
  "/worlds/world-event.jpg": {
    "width": 1792,
    "height": 907
  },
  "/worlds/world-install.jpg": {
    "width": 1792,
    "height": 907
  },
  "/products/gold-ice.jpg": {
    "width": 650,
    "height": 650
  },
  "/products/goldy-hero.jpg": {
    "width": 1600,
    "height": 1280
  },
  "/products/goldy.jpg": {
    "width": 1400,
    "height": 1400
  },
  "/products/h50.jpg": {
    "width": 650,
    "height": 650
  },
  "/products/picky.jpg": {
    "width": 650,
    "height": 650
  },
  "/products/v100-portable.jpg": {
    "width": 1400,
    "height": 1400
  },
  "/products/v100.jpg": {
    "width": 1400,
    "height": 1400
  },
  "/products/v200-portable.jpg": {
    "width": 650,
    "height": 650
  },
  "/products/v200.jpg": {
    "width": 1400,
    "height": 1400
  },
  "/products/v300.jpg": {
    "width": 650,
    "height": 650
  },
  "/products/v500.jpg": {
    "width": 650,
    "height": 650
  },
  "/products/v90.jpg": {
    "width": 650,
    "height": 650
  }
};
