import { withBase } from "./base";
import type { Product } from "./products";

/** Auto-generated catalog extras — do not edit by hand. */
export const productsExtra: Product[] = [
  {
    id: "serpentijnen-bier",
    index: "22",
    name: "Serpentijnen bier",
    badge: "Serpentijnen · Bier",
    description: "RVS-serpentijnen voor bier, voedselveilig en leverbaar in meerdere lengtes.",
    longDescription: "Serpentijnen bier in roestvrij staal, goedgekeurd voor voedingsgebruik. Beschikbaar in diverse buislengtes (o.a. 3–27 m) en diameters Ø7/Ø8. Ideaal voor ijsbankkoelers en vaste taplijnen via VanRobi.",
    image: withBase("/assets/products-catalog/serpentijnen-bier.jpg"),
    alt: "Serpentijnen bier, via VanRobi België & Nederland",
    cropClass: "crop-serpentijnen-bier",
    uses: ["horeca", "onder-bar"],
    group: "serpentijnen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Materiaal", value: "RVS" },
      { label: "Buisdiameter", value: "Ø 8, Ø7" },
      { label: "Buislengte (m)", value: "27, 26, 22, 17, 16, 12, 9, 8, 3" }
    ],
  },
  {
    id: "serpentijnen-bier-helicoidal",
    index: "23",
    name: "Serpentijnen bier helicoidal",
    badge: "Serpentijnen · Helicoidal",
    description: "Helicoidale RVS-serpentijnen voor bier, compacte spoelvorm.",
    longDescription: "Helicoidale serpentijnen bier in RVS voor compacte spoelopbouw in de ijsbank. Voedselveilig, typische buislengte ±27 m. Via VanRobi voor horeca en installateurs in BE & NL.",
    image: withBase("/assets/products-catalog/serpentijnen-bier-helicoidal.jpg"),
    alt: "Serpentijnen bier helicoidal, via VanRobi België & Nederland",
    cropClass: "crop-serpentijnen-bier-helicoidal",
    uses: ["horeca", "onder-bar"],
    group: "serpentijnen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Materiaal", value: "RVS" },
      { label: "Buisdiameter", value: "Ø 8, Ø7" },
      { label: "Buislengte (m)", value: "27" }
    ],
  },
  {
    id: "serpentijnen-bier-alcoholvrij",
    index: "24",
    name: "Serpentijnen bier alcoholvrij",
    badge: "Serpentijnen · Alcoholvrij",
    description: "RVS-serpentijnen afgestemd op alcoholvrij bier.",
    longDescription: "Serpentijnen voor alcoholvrij bier in roestvrij staal. Zelfde voedselveilige kwaliteit als de bierlijn, met lengtes van 3 tot 27 m. Via VanRobi.",
    image: withBase("/assets/products-catalog/serpentijnen-bier-alcoholvrij.jpg"),
    alt: "Serpentijnen bier alcoholvrij, via VanRobi België & Nederland",
    cropClass: "crop-serpentijnen-bier-alcoholvrij",
    uses: ["horeca", "onder-bar"],
    group: "serpentijnen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Materiaal", value: "RVS" },
      { label: "Buisdiameter", value: "Ø 8, Ø7" },
      { label: "Buislengte (m)", value: "27, 26, 22, 17, 16, 12, 9, 8, 3" }
    ],
  },
  {
    id: "serpentijnen-sangria-frisdrank",
    index: "25",
    name: "Serpentijnen sangria/frisdrank",
    badge: "Serpentijnen · Frisdrank",
    description: "RVS-serpentijnen voor sangria en frisdrank.",
    longDescription: "Serpentijnen voor sangria en frisdrank in RVS Ø7, typische lengtes 8–9 m. Voor bars en events die meer dan bier tapen. Via VanRobi.",
    image: withBase("/assets/products-catalog/serpentijnen-sangria-frisdrank.jpg"),
    alt: "Serpentijnen sangria/frisdrank, via VanRobi België & Nederland",
    cropClass: "crop-serpentijnen-sangria-frisdrank",
    uses: ["horeca", "events"],
    group: "serpentijnen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Materiaal", value: "RVS" },
      { label: "Buisdiameter", value: "Ø7" },
      { label: "Buislengte (m)", value: "9, 8" }
    ],
  },
  {
    id: "serpentijnen-cider",
    index: "26",
    name: "Serpentijnen cider",
    badge: "Serpentijnen · Cider",
    description: "RVS 316-serpentijnen voor cider/sidra.",
    longDescription: "Serpentijnen cider in RVS 316, voedselveilig. Buisdiameter Ø7, lengtes o.a. 11–12 m. Speciaal voor ciderlijnen via VanRobi.",
    image: withBase("/assets/products-catalog/serpentijnen-cider.jpg"),
    alt: "Serpentijnen cider, via VanRobi België & Nederland",
    cropClass: "crop-serpentijnen-cider",
    uses: ["horeca", "onder-bar"],
    group: "serpentijnen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Materiaal", value: "RVS 316" },
      { label: "Buisdiameter", value: "Ø7" },
      { label: "Buislengte (m)", value: "12, 11" }
    ],
  },
  {
    id: "serpentijnen-water",
    index: "27",
    name: "Serpentijnen water",
    badge: "Serpentijnen · Water",
    description: "RVS-serpentijnen voor gekoeld water.",
    longDescription: "Serpentijnen water in RVS Ø8, lengtes o.a. 3–7 m. Voor waterkoeling in tap- of procesopstellingen. Via VanRobi BE & NL.",
    image: withBase("/assets/products-catalog/serpentijnen-water.jpg"),
    alt: "Serpentijnen water, via VanRobi België & Nederland",
    cropClass: "crop-serpentijnen-water",
    uses: ["horeca"],
    group: "serpentijnen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Materiaal", value: "RVS" },
      { label: "Buisdiameter", value: "Ø8" },
      { label: "Buislengte (m)", value: "7, 3" }
    ],
  },
  {
    id: "serpentijnen-op-maat",
    index: "28",
    name: "Serpentijnen op maat",
    badge: "Serpentijnen · Op maat",
    description: "Serpentijnen op maat voor speciale volumes en layouts.",
    longDescription: "Serpentijnen op maat wanneer standaardlengtes niet passen. VanRobi stemt spoel, diameter en materiaal af op uw ijsbank en debiet.",
    image: withBase("/assets/products-catalog/serpentijnen-op-maat.jpg"),
    alt: "Serpentijnen op maat, via VanRobi België & Nederland",
    cropClass: "crop-serpentijnen-op-maat",
    uses: ["horeca", "onder-bar"],
    group: "serpentijnen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Diámetros de tubo", value: "Ø6, Ø7 , Ø8 ¡Pregúntanos por materiales y las medidas que necesitas!" }
    ],
  },
  {
    id: "mojacopas",
    index: "29",
    name: "Glasreiniger (mojacopas)",
    badge: "Dispensing · Mojacopas",
    description: "Mojacopas-glasreiniger voor nette tapafwerking.",
    longDescription: "Mojacopas (glasreiniger) voor professionele tapstations. Houdt glazen schoon en presentatie strak. Via VanRobi.",
    image: withBase("/assets/products-catalog/mojacopas.jpg"),
    alt: "Glasreiniger (mojacopas), via VanRobi België & Nederland",
    cropClass: "crop-mojacopas",
    uses: ["horeca"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Fabricada en RVS o plástico" }
    ],
  },
  {
    id: "manorreductor-1",
    index: "30",
    name: "Drukregelaar 1 product",
    badge: "Dispensing · CO₂",
    description: "Manorreductor/drukregelaar voor één dranklijn.",
    longDescription: "Drukregelaar (manorreductor) voor één productlijn. Stabiele CO₂- of gasdruk voor consistente tapkwaliteit via VanRobi.",
    image: withBase("/assets/products-catalog/manorreductor-1.jpg"),
    alt: "Drukregelaar 1 product, via VanRobi België & Nederland",
    cropClass: "crop-manorreductor-1",
    uses: ["horeca", "events"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "1 Esfera de alta y 1 esfera de baja" },
      { label: "Info", value: "Esferas protegidas con funda de plástico amortigua golpes" }
    ],
  },
  {
    id: "manorreductor-2",
    index: "31",
    name: "Drukregelaar 2 producten",
    badge: "Dispensing · CO₂",
    description: "Drukregelaar voor twee dranklijnen.",
    longDescription: "Manorreductor voor twee producten. Ideaal wanneer u twee bieren of mix van bier/frisdrank tapt. Via VanRobi.",
    image: withBase("/assets/products-catalog/manorreductor-2.jpg"),
    alt: "Drukregelaar 2 producten, via VanRobi België & Nederland",
    cropClass: "crop-manorreductor-2",
    uses: ["horeca", "events"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "2 Esfera de alta y 1 esfera de baja" },
      { label: "Info", value: "Esferas protegidas con funda de plástico amortigua golpes" }
    ],
  },
  {
    id: "manorreductor-3",
    index: "32",
    name: "Drukregelaar 3 producten",
    badge: "Dispensing · CO₂",
    description: "Drukregelaar voor drie dranklijnen.",
    longDescription: "Manorreductor voor drie productlijnen. Voor bars met een breder tapaanbod. Leverbaar via VanRobi BE & NL.",
    image: withBase("/assets/products-catalog/manorreductor-3.jpg"),
    alt: "Drukregelaar 3 producten, via VanRobi België & Nederland",
    cropClass: "crop-manorreductor-3",
    uses: ["horeca"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "3 Esfera de alta y 1 esfera de baja" },
      { label: "Info", value: "Esferas protegidas con funda de plastico amortigua golpes" }
    ],
  },
  {
    id: "bierleiding",
    index: "33",
    name: "Bierleiding",
    badge: "Onderdelen · Leiding",
    description: "Professionele bierslang/leiding voor tapinstallaties.",
    longDescription: "Bierleiding voor professionele tapinstallaties. Passend bij serpentijnen, kranen en koelers in het VanRobi-assortiment.",
    image: withBase("/assets/products-catalog/bierleiding.jpg"),
    alt: "Bierleiding, via VanRobi België & Nederland",
    cropClass: "crop-bierleiding",
    uses: ["horeca", "onder-bar"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Varias medidas", value: "Tubo lupulus 5/16″ – especial – Tubo lupulus 7 x 10 mm Tubo lupulus 6,7 x 9,5 mm" }
    ],
  },
  {
    id: "sin-bomba",
    index: "34",
    name: "Koeler zonder pomp",
    badge: "Koelers · Configuratie",
    description: "Configuratie zonder pomp voor specifieke ijsbankopstellingen.",
    longDescription: "Variant zonder pomp wanneer de installatie circulatie elders regelt. VanRobi adviseert over de juiste pomp/configuratie.",
    image: withBase("/assets/products-catalog/sin-bomba.jpg"),
    alt: "Koeler zonder pomp, via VanRobi België & Nederland",
    cropClass: "crop-sin-bomba",
    uses: ["horeca"],
    group: "koelers",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Specificaties", value: "V 220/ V 115, Hz 50/ 60 Hz, W 55" },
      { label: "Info", value: "Anti-vibratiesysteem" }
    ],
  },
  {
    id: "tapzuil-circulair-dubbel",
    index: "35",
    name: "Tapzuil circulair dubbel",
    badge: "Dispensing · Zuil",
    description: "Ronde dubbele tapzuil voor twee kranen.",
    longDescription: "Circulaire dubbele tapzuil voor twee services. Zichtbare barpresentatie met professionele afwerking via VanRobi.",
    image: withBase("/assets/products-catalog/tapzuil-circulair-dubbel.jpg"),
    alt: "Tapzuil circulair dubbel, via VanRobi België & Nederland",
    cropClass: "crop-tapzuil-circulair-dubbel",
    uses: ["horeca", "events"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Merk", value: "VanRobi · BE & NL" },
      { label: "Leverancier", value: "VanRobi · België & Nederland" }
    ],
  },
  {
    id: "bandeja-1-zonder-mojacopas",
    index: "36",
    name: "Lekbak 1 service zonder mojacopas",
    badge: "Dispensing · Lekbak",
    description: "Lekbak voor 1 kraan, zonder mojacopas.",
    longDescription: "RVS-lekbak (bandeja) voor één service, zonder glasreiniger. Netjes afgewerkt onder de kraan. Via VanRobi.",
    image: withBase("/assets/products-catalog/bandeja-1-zonder-mojacopas.jpg"),
    alt: "Lekbak 1 service zonder mojacopas, via VanRobi België & Nederland",
    cropClass: "crop-bandeja-1-zonder-mojacopas",
    uses: ["horeca"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Fabricada en RVS" },
      { label: "Info", value: "Dispone de desague para vaciado y limpieza" }
    ],
  },
  {
    id: "bandeja-2-zonder-mojacopas",
    index: "37",
    name: "Lekbak 2 services zonder mojacopas",
    badge: "Dispensing · Lekbak",
    description: "Lekbak voor 2 kranen, zonder mojacopas.",
    longDescription: "Lekbak voor twee services zonder mojacopas. Passend bij dubbele zuilen. Via VanRobi.",
    image: withBase("/assets/products-catalog/bandeja-2-zonder-mojacopas.jpg"),
    alt: "Lekbak 2 services zonder mojacopas, via VanRobi België & Nederland",
    cropClass: "crop-bandeja-2-zonder-mojacopas",
    uses: ["horeca"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Fabricada en RVS" },
      { label: "Info", value: "Dispone de desagüe para vaciado y limpieza" }
    ],
  },
  {
    id: "bandeja-3-met-mojacopas",
    index: "38",
    name: "Lekbak 3 services met mojacopas",
    badge: "Dispensing · Lekbak",
    description: "Lekbak voor 3 kranen, met mojacopas.",
    longDescription: "Lekbak voor drie services met mojacopas. Via VanRobi.",
    image: withBase("/assets/products-catalog/bandeja-3-met-mojacopas.jpg"),
    alt: "Lekbak 3 services met mojacopas, via VanRobi België & Nederland",
    cropClass: "crop-bandeja-3-met-mojacopas",
    uses: ["horeca"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Fabricada en RVS" },
      { label: "Info", value: "Dispone de desagüe para vaciado y limpieza" }
    ],
  },
  {
    id: "bandeja-3-zonder-mojacopas",
    index: "39",
    name: "Lekbak 3 services zonder mojacopas",
    badge: "Dispensing · Lekbak",
    description: "Lekbak voor 3 kranen, zonder mojacopas.",
    longDescription: "Lekbak voor drie services zonder mojacopas. Voor bredere tapstations. Via VanRobi.",
    image: withBase("/assets/products-catalog/bandeja-3-zonder-mojacopas.jpg"),
    alt: "Lekbak 3 services zonder mojacopas, via VanRobi België & Nederland",
    cropClass: "crop-bandeja-3-zonder-mojacopas",
    uses: ["horeca"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Fabricada en RVS" },
      { label: "Info", value: "Dispone de desagüe para vaciado y limpieza" }
    ],
  },
  {
    id: "bandeja-4-plus",
    index: "40",
    name: "Lekbak 4+ services",
    badge: "Dispensing · Lekbak",
    description: "Lekbak voor 4 of meer kranen.",
    longDescription: "Lekbak voor vier of meer services. Voor high-volume bars en festivalbars. Via VanRobi.",
    image: withBase("/assets/products-catalog/bandeja-4-plus.jpg"),
    alt: "Lekbak 4+ services, via VanRobi België & Nederland",
    cropClass: "crop-bandeja-4-plus",
    uses: ["horeca", "events"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Fabricada en RVS" },
      { label: "Info", value: "Dispone de desagüe para vaciado y limpieza" }
    ],
  },
  {
    id: "manorreductor-4",
    index: "41",
    name: "Drukregelaar 4 producten",
    badge: "Dispensing · CO₂",
    description: "Drukregelaar voor vier dranklijnen.",
    longDescription: "Manorreductor voor vier producten. High-volume tapstations met meerdere lijnen. Via VanRobi.",
    image: withBase("/assets/products-catalog/manorreductor-4.jpg"),
    alt: "Drukregelaar 4 producten, via VanRobi België & Nederland",
    cropClass: "crop-manorreductor-4",
    uses: ["horeca"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "4 Esfera de alta y 1 esfera de baja" },
      { label: "Info", value: "Esferas protegidas con funda de plástico amortigua golpes" }
    ],
  },
  {
    id: "tapzuilen-afwerkingen",
    index: "42",
    name: "Tapzuilen diverse afwerkingen",
    badge: "Dispensing · Zuil",
    description: "Tapzuilen met verschillende afwerkingen en finishes.",
    longDescription: "Tapzuilen met diverse afwerkingen — kies look en materiaal passend bij uw bar. VanRobi helpt bij selectie.",
    image: withBase("/assets/products-catalog/tapzuilen-afwerkingen.jpg"),
    alt: "Tapzuilen diverse afwerkingen, via VanRobi België & Nederland",
    cropClass: "crop-tapzuilen-afwerkingen",
    uses: ["horeca", "events"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Merk", value: "VanRobi · BE & NL" },
      { label: "Leverancier", value: "VanRobi · België & Nederland" }
    ],
  },
  {
    id: "kranen-rvs",
    index: "43",
    name: "RVS-tapkranen",
    badge: "Dispensing · Kranen",
    description: "Professionele RVS-tapkranen voor bier en frisdrank.",
    longDescription: "Roestvrijstalen tapkranen voor horeca en events. Passend bij zuilen, serpentijnen en ijsbankkoelers in het VanRobi-assortiment.",
    image: withBase("/assets/products-catalog/kranen-rvs.jpg"),
    alt: "RVS-tapkranen, via VanRobi België & Nederland",
    cropClass: "crop-kranen-rvs",
    uses: ["horeca", "events"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Merk", value: "VanRobi · BE & NL" },
      { label: "Leverancier", value: "VanRobi · België & Nederland" }
    ],
  },
  {
    id: "kranen-water-rvs",
    index: "44",
    name: "RVS-waterkranen",
    badge: "Dispensing · Water",
    description: "RVS-kranen voor gekoeld water aan de bar.",
    longDescription: "Roestvrijstalen waterkranen voor gekoeld water in horeca-opstellingen. Combineerbaar met water-serpentijnen via VanRobi.",
    image: withBase("/assets/products-catalog/kranen-water-rvs.jpg"),
    alt: "RVS-waterkranen, via VanRobi België & Nederland",
    cropClass: "crop-kranen-water-rvs",
    uses: ["horeca"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Merk", value: "VanRobi · BE & NL" },
      { label: "Leverancier", value: "VanRobi · België & Nederland" }
    ],
  },
  {
    id: "kraanstaart-45",
    index: "45",
    name: "Kraanstaart 45 tanden",
    badge: "Dispensing · Koppeling",
    description: "Cola/kraanstaart 45 tanden voor kraan–zuil verbinding.",
    longDescription: "Kraanstaart (cola) 45 tanden voor betrouwbare verbinding tussen kraan en zuil. Onderdeel van de VanRobi dispensing-lijn.",
    image: withBase("/assets/products-catalog/kraanstaart-45.jpg"),
    alt: "Kraanstaart 45 tanden, via VanRobi België & Nederland",
    cropClass: "crop-kraanstaart-45",
    uses: ["horeca"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Merk", value: "VanRobi · BE & NL" },
      { label: "Leverancier", value: "VanRobi · België & Nederland" }
    ],
  },
  {
    id: "tapzuil-circulair",
    index: "46",
    name: "Tapzuil circulair",
    badge: "Dispensing · Zuil",
    description: "Ronde enkele tapzuil.",
    longDescription: "Circulaire enkele tapzuil voor één kraan. Klassieke look voor bars en events. Via VanRobi.",
    image: withBase("/assets/products-catalog/tapzuil-circulair.jpg"),
    alt: "Tapzuil circulair, via VanRobi België & Nederland",
    cropClass: "crop-tapzuil-circulair",
    uses: ["horeca", "events"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Merk", value: "VanRobi · BE & NL" },
      { label: "Leverancier", value: "VanRobi · België & Nederland" }
    ],
  },
  {
    id: "tapzuil-boa",
    index: "47",
    name: "Tapzuil Boa",
    badge: "Dispensing · Zuil",
    description: "Tapzuil Boa, enkele uitvoering.",
    longDescription: "Tapzuil Boa in enkele uitvoering. Designzuil voor craftbars en horeca. Leverbaar via VanRobi.",
    image: withBase("/assets/products-catalog/tapzuil-boa.jpg"),
    alt: "Tapzuil Boa, via VanRobi België & Nederland",
    cropClass: "crop-tapzuil-boa",
    uses: ["horeca", "events"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Merk", value: "VanRobi · BE & NL" },
      { label: "Leverancier", value: "VanRobi · België & Nederland" }
    ],
  },
  {
    id: "medaillon-tapzuil",
    index: "48",
    name: "Medaillon voor tapzuil",
    badge: "Dispensing · Accessoire",
    description: "Medaillon/badge voor branding op de tapzuil.",
    longDescription: "Medaillon voor tapzuilen: plaats merk of productnaam zichtbaar aan de bar. Via VanRobi.",
    image: withBase("/assets/products-catalog/medaillon-tapzuil.jpg"),
    alt: "Medaillon voor tapzuil, via VanRobi België & Nederland",
    cropClass: "crop-medaillon-tapzuil",
    uses: ["horeca"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Varianten", value: "Medaillon embleem circulaire zuil · Medaillon embleem zuil BOA" }
    ],
  },
  {
    id: "bandeja-1-met-mojacopas",
    index: "49",
    name: "Lekbak 1 service met mojacopas",
    badge: "Dispensing · Lekbak",
    description: "Lekbak voor 1 kraan, met mojacopas.",
    longDescription: "Lekbak voor één service met geïntegreerde mojacopas. Voor nette glazen en hygiënische tap. Via VanRobi.",
    image: withBase("/assets/products-catalog/bandeja-1-met-mojacopas.jpg"),
    alt: "Lekbak 1 service met mojacopas, via VanRobi België & Nederland",
    cropClass: "crop-bandeja-1-met-mojacopas",
    uses: ["horeca"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Fabricada en RVS" },
      { label: "Info", value: "Dispone de desague para vaciado y limpieza" }
    ],
  },
  {
    id: "bandeja-2-met-mojacopas",
    index: "50",
    name: "Lekbak 2 services met mojacopas",
    badge: "Dispensing · Lekbak",
    description: "Lekbak voor 2 kranen, met mojacopas.",
    longDescription: "Lekbak voor twee services met mojacopas. Via VanRobi voor horeca in BE & NL.",
    image: withBase("/assets/products-catalog/bandeja-2-met-mojacopas.jpg"),
    alt: "Lekbak 2 services met mojacopas, via VanRobi België & Nederland",
    cropClass: "crop-bandeja-2-met-mojacopas",
    uses: ["horeca"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Fabricada en RVS" },
      { label: "Info", value: "Dispone de desagüe para vaciado y limpieza" }
    ],
  },
  {
    id: "steun-lekbak",
    index: "51",
    name: "Steun voor lekbak",
    badge: "Dispensing · Steun",
    description: "Montagesteun voor lekbakken.",
    longDescription: "Steun/montage voor lekbakken. Stabiele bevestiging aan bar of zuil. Via VanRobi.",
    image: withBase("/assets/products-catalog/steun-lekbak.jpg"),
    alt: "Steun voor lekbak, via VanRobi België & Nederland",
    cropClass: "crop-steun-lekbak",
    uses: ["horeca"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Fabricada en RVS y en varias medidas" }
    ],
  },
  {
    id: "koppeling-type-a",
    index: "52",
    name: "Vatkoppeling type A",
    badge: "Dispensing · Koppeling",
    description: "Vacuümkoppeling type A voor vaten.",
    longDescription: "Vatkoppeling type A (cabezal vacío). Voor standaard vatinterfaces in horeca. Via VanRobi.",
    image: withBase("/assets/products-catalog/koppeling-type-a.jpg"),
    alt: "Vatkoppeling type A, via VanRobi België & Nederland",
    cropClass: "crop-koppeling-type-a",
    uses: ["horeca", "events"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Brida circular" },
      { label: "Info", value: "Acoplamiento por desplazamiento" },
      { label: "Info", value: "Pistón de RVS" }
    ],
  },
  {
    id: "koppeling-type-s",
    index: "53",
    name: "Vatkoppeling type S",
    badge: "Dispensing · Koppeling",
    description: "Vacuümkoppeling type S voor vaten.",
    longDescription: "Vatkoppeling type S. Passend bij specifieke vatstandaarden. Via VanRobi BE & NL.",
    image: withBase("/assets/products-catalog/koppeling-type-s.jpg"),
    alt: "Vatkoppeling type S, via VanRobi België & Nederland",
    cropClass: "crop-koppeling-type-s",
    uses: ["horeca", "events"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "2 enganches" },
      { label: "Info", value: "Acoplamiento por giro con tope" },
      { label: "Info", value: "Pistón RVS" }
    ],
  },
  {
    id: "koppeling-type-g",
    index: "54",
    name: "Vatkoppeling type G",
    badge: "Dispensing · Koppeling",
    description: "Vacuümkoppeling type G voor vaten.",
    longDescription: "Vatkoppeling type G. Voor G-type vatinterfaces. Leverbaar via VanRobi.",
    image: withBase("/assets/products-catalog/koppeling-type-g.jpg"),
    alt: "Vatkoppeling type G, via VanRobi België & Nederland",
    cropClass: "crop-koppeling-type-g",
    uses: ["horeca", "events"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Brida trilobular" },
      { label: "Info", value: "Acoplamiento por giro con tope" },
      { label: "Info", value: "Pistón RVS" }
    ],
  },
  {
    id: "koppeling-key-keg",
    index: "55",
    name: "Vatkoppeling KeyKeg",
    badge: "Dispensing · KeyKeg",
    description: "Koppeling voor KeyKeg-vaten.",
    longDescription: "KeyKeg-koppeling voor craft en events. Snel wisselen van vaten zonder klassieke speerpunt. Via VanRobi.",
    image: withBase("/assets/products-catalog/koppeling-key-keg.jpg"),
    alt: "Vatkoppeling KeyKeg, via VanRobi België & Nederland",
    cropClass: "crop-koppeling-key-keg",
    uses: ["horeca", "events", "mobiel"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "3 enganches" },
      { label: "Info", value: "Acoplamiento por giro con tope" },
      { label: "Info", value: "Pistón RVS" }
    ],
  },
  {
    id: "ball-lock-gas",
    index: "56",
    name: "Ball lock gas",
    badge: "Dispensing · Ball lock",
    description: "Ball-lock koppeling voor gaszijde.",
    longDescription: "Ball-lock koppeling gas. Voor systemen met ball-lock interfaces (o.a. Cornelius-stijl). Via VanRobi.",
    image: withBase("/assets/products-catalog/ball-lock-gas.jpg"),
    alt: "Ball lock gas, via VanRobi België & Nederland",
    cropClass: "crop-ball-lock-gas",
    uses: ["horeca", "events"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "1 entrada" },
      { label: "Info", value: "Acoplamiento a presión" }
    ],
  },
  {
    id: "ball-lock-vloeistof",
    index: "57",
    name: "Ball lock vloeistof",
    badge: "Dispensing · Ball lock",
    description: "Ball-lock koppeling voor vloeistofzijde.",
    longDescription: "Ball-lock koppeling vloeistof. Combineer met ball-lock gas voor complete disconnects. Via VanRobi.",
    image: withBase("/assets/products-catalog/ball-lock-vloeistof.jpg"),
    alt: "Ball lock vloeistof, via VanRobi België & Nederland",
    cropClass: "crop-ball-lock-vloeistof",
    uses: ["horeca", "events"],
    group: "dispensing",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "1 entrada" },
      { label: "Info", value: "Acoplamiento a presión" }
    ],
  },
  {
    id: "thermostaat-elektronisch",
    index: "58",
    name: "Elektronische thermostaat",
    badge: "Onderdelen · Regeling",
    description: "Elektronische thermostaat voor ijsbankkoelers.",
    longDescription: "Elektronische thermostaat voor nauwkeurige temperatuurregeling van ijsbankkoelers. Vervanging of upgrade via VanRobi.",
    image: withBase("/assets/products-catalog/thermostaat-elektronisch.jpg"),
    alt: "Elektronische thermostaat, via VanRobi België & Nederland",
    cropClass: "crop-thermostaat-elektronisch",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Amplia gama de modelos" }
    ],
  },
  {
    id: "thermostaat-digitaal",
    index: "59",
    name: "Digitale thermostaat",
    badge: "Onderdelen · Regeling",
    description: "Digitale thermostaat met display.",
    longDescription: "Digitale thermostaat met duidelijke uitlezing. Voor professionele koelregeling via VanRobi.",
    image: withBase("/assets/products-catalog/thermostaat-digitaal.jpg"),
    alt: "Digitale thermostaat, via VanRobi België & Nederland",
    cropClass: "crop-thermostaat-digitaal",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Amplia gama de modelos" }
    ],
  },
  {
    id: "thermostaat-mechanisch",
    index: "60",
    name: "Mechanische thermostaat",
    badge: "Onderdelen · Regeling",
    description: "Mechanische thermostaat voor koelers.",
    longDescription: "Robuuste mechanische thermostaat voor ijsbank- en vatkoelers. Via VanRobi.",
    image: withBase("/assets/products-catalog/thermostaat-mechanisch.jpg"),
    alt: "Mechanische thermostaat, via VanRobi België & Nederland",
    cropClass: "crop-thermostaat-mechanisch",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Amplia gama de modelos" }
    ],
  },
  {
    id: "sonde-digitaal",
    index: "61",
    name: "Digitale/elektronische sonde",
    badge: "Onderdelen · Sensor",
    description: "Temperatuursensor/sonde voor koelregeling.",
    longDescription: "Elektronische/digitale temperatuursensor voor thermostaten en regelingen. Via VanRobi.",
    image: withBase("/assets/products-catalog/sonde-digitaal.jpg"),
    alt: "Digitale/elektronische sonde, via VanRobi België & Nederland",
    cropClass: "crop-sonde-digitaal",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Amplia gama de modelos" }
    ],
  },
  {
    id: "relais-compressor",
    index: "62",
    name: "Relais compressor",
    badge: "Onderdelen · Elektrisch",
    description: "Compressorrelais voor start/bedrijf.",
    longDescription: "Relais voor compressormotoren in ijsbankkoelers. Onderhoudsonderdeel via VanRobi.",
    image: withBase("/assets/products-catalog/relais-compressor.jpg"),
    alt: "Relais compressor, via VanRobi België & Nederland",
    cropClass: "crop-relais-compressor",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Amplia gama de modelos" }
    ],
  },
  {
    id: "startcondensator-compressor",
    index: "63",
    name: "Startcondensator compressor",
    badge: "Onderdelen · Elektrisch",
    description: "Startcondensator voor compressormotor.",
    longDescription: "Startcondensator voor compressoren. Vervangingsonderdeel via VanRobi BE & NL.",
    image: withBase("/assets/products-catalog/startcondensator-compressor.jpg"),
    alt: "Startcondensator compressor, via VanRobi België & Nederland",
    cropClass: "crop-startcondensator-compressor",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Amplia gama de modelos" }
    ],
  },
  {
    id: "filter-moleculair-20g",
    index: "64",
    name: "Moleculair filter 20 g",
    badge: "Onderdelen · Filter",
    description: "Moleculair filter 20 gram voor koelcircuit.",
    longDescription: "Moleculair filter 20 g voor het koelcircuit. Onderhoudsonderdeel via VanRobi.",
    image: withBase("/assets/products-catalog/filter-moleculair-20g.jpg"),
    alt: "Moleculair filter 20 g, via VanRobi België & Nederland",
    cropClass: "crop-filter-moleculair-20g",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Merk", value: "VanRobi · BE & NL" },
      { label: "Leverancier", value: "VanRobi · België & Nederland" }
    ],
  },
  {
    id: "filter-ceramisch-32s",
    index: "65",
    name: "Keramisch filter 32 S",
    badge: "Onderdelen · Filter",
    description: "Keramisch filter 32 S.",
    longDescription: "Keramisch filter type 32 S voor koel- of watercircuits. Via VanRobi.",
    image: withBase("/assets/products-catalog/filter-ceramisch-32s.jpg"),
    alt: "Keramisch filter 32 S, via VanRobi België & Nederland",
    cropClass: "crop-filter-ceramisch-32s",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Merk", value: "VanRobi · BE & NL" },
      { label: "Leverancier", value: "VanRobi · België & Nederland" }
    ],
  },
  {
    id: "ventilator",
    index: "66",
    name: "Ventilator",
    badge: "Onderdelen · Koeling",
    description: "Ventilator voor condensor of unitkoeling.",
    longDescription: "Ventilator voor warmteafvoer van condensors en units. Vervanging via VanRobi.",
    image: withBase("/assets/products-catalog/ventilator.jpg"),
    alt: "Ventilator, via VanRobi België & Nederland",
    cropClass: "crop-ventilator",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "5W/10W/18W/ 25W" }
    ],
  },
  {
    id: "wielen",
    index: "67",
    name: "Wielen",
    badge: "Onderdelen · Mobiel",
    description: "Wielen voor portable koelers.",
    longDescription: "Wielen/set voor mobiele ijsbankkoelers. Voor events en snelle verplaatsing. Via VanRobi.",
    image: withBase("/assets/products-catalog/wielen.jpg"),
    alt: "Wielen, via VanRobi België & Nederland",
    cropClass: "crop-wielen",
    uses: ["events", "mobiel"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Merk", value: "VanRobi · BE & NL" },
      { label: "Leverancier", value: "VanRobi · België & Nederland" }
    ],
  },
  {
    id: "bevestigingsklemmen",
    index: "68",
    name: "Bevestigingsklemmen",
    badge: "Onderdelen · Montage",
    description: "Klemmen voor leiding- en slangmontage.",
    longDescription: "Bevestigingsklemmen (abrazaderas) voor slangen en leidingen. Via VanRobi.",
    image: withBase("/assets/products-catalog/bevestigingsklemmen.jpg"),
    alt: "Bevestigingsklemmen, via VanRobi België & Nederland",
    cropClass: "crop-bevestigingsklemmen",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Amplia gama de modelos y medidas", value: "Abrazadera 10.9 Abrazadera 11.8 Abrazadera 12.8 Abrazadera 14.0 Abrazadera 15…" }
    ],
  },
  {
    id: "flenzen",
    index: "69",
    name: "Flenzen",
    badge: "Onderdelen · Montage",
    description: "Flenzen voor leidingverbindingen.",
    longDescription: "Flenzen (bridas) voor vaste leidingverbindingen in tap- en koelinstallaties. Via VanRobi.",
    image: withBase("/assets/products-catalog/flenzen.jpg"),
    alt: "Flenzen, via VanRobi België & Nederland",
    cropClass: "crop-flenzen",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Amplia gama de modelos y medidas", value: "Brida grande CV 280 Brida grande CV 280 negra Brida mediana CV 200 Brida pequ…" }
    ],
  },
  {
    id: "snelkoppelingen",
    index: "70",
    name: "Snelkoppelingen",
    badge: "Onderdelen · Koppeling",
    description: "Snelkoppelingen voor flexibele installaties.",
    longDescription: "Snelkoppelingen voor snelle opbouw van taplijnen, ideaal bij events. Via VanRobi.",
    image: withBase("/assets/products-catalog/snelkoppelingen.jpg"),
    alt: "Snelkoppelingen, via VanRobi België & Nederland",
    cropClass: "crop-snelkoppelingen",
    uses: ["horeca", "events", "mobiel"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Amplia gama de modelos" }
    ],
  },
  {
    id: "bocht-retourkoeling",
    index: "71",
    name: "Bocht retourkoeling",
    badge: "Onderdelen · Leiding",
    description: "Bochtstuk voor retourkoelleiding.",
    longDescription: "Bocht voor retourkoeling in glycol- of watercircuits. Via VanRobi.",
    image: withBase("/assets/products-catalog/bocht-retourkoeling.jpg"),
    alt: "Bocht retourkoeling, via VanRobi België & Nederland",
    cropClass: "crop-bocht-retourkoeling",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "PLÁSTICO" }
    ],
  },
  {
    id: "y-stuk-water",
    index: "72",
    name: "Y-stuk water 2 uitgangen",
    badge: "Onderdelen · Verdeel",
    description: "Y-verdeelstuk voor water, 2 uitgangen.",
    longDescription: "Y-bifurcatie met twee wateruitgangen voor irrigatie/circulatie. Via VanRobi.",
    image: withBase("/assets/products-catalog/y-stuk-water.jpg"),
    alt: "Y-stuk water 2 uitgangen, via VanRobi België & Nederland",
    cropClass: "crop-y-stuk-water",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "PLÁSTICO" }
    ],
  },
  {
    id: "y-stuk-co2",
    index: "73",
    name: "Y-stuk CO₂ versterkt",
    badge: "Onderdelen · Verdeel",
    description: "Versterkt Y-stuk voor CO₂, 2 uitgangen.",
    longDescription: "Versterkt Y-stuk voor CO₂-verdeling over twee lijnen. Via VanRobi.",
    image: withBase("/assets/products-catalog/y-stuk-co2.jpg"),
    alt: "Y-stuk CO₂ versterkt, via VanRobi België & Nederland",
    cropClass: "crop-y-stuk-co2",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "PLÁSTICO" }
    ],
  },
  {
    id: "rubberdoppen-overstroming",
    index: "74",
    name: "Rubberdoppen overstroming",
    badge: "Onderdelen · Afdichting",
    description: "Rubberdoppen voor overstromings-/irrigatieopeningen.",
    longDescription: "Rubberdoppen voor afdichting van overstromingsopeningen in ijsbanken. Via VanRobi.",
    image: withBase("/assets/products-catalog/rubberdoppen-overstroming.jpg"),
    alt: "Rubberdoppen overstroming, via VanRobi België & Nederland",
    cropClass: "crop-rubberdoppen-overstroming",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "1 – 4 agujeros" }
    ],
  },
  {
    id: "glycol",
    index: "75",
    name: "Glycolvloeistof",
    badge: "Onderdelen · Glycol",
    description: "Glycol voor gesloten koelcircuits.",
    longDescription: "Glycolvloeistof voor gesloten koelcircuits en glycolvarianten van ijsbankkoelers. Via VanRobi.",
    image: withBase("/assets/products-catalog/glycol.jpg"),
    alt: "Glycolvloeistof, via VanRobi België & Nederland",
    cropClass: "crop-glycol",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Botella de 10 litros" }
    ],
  },
  {
    id: "aansluiting-pompuitgang",
    index: "76",
    name: "Aansluiting pompuitgang",
    badge: "Onderdelen · Pomp",
    description: "Aansluiting voor pompuitgang.",
    longDescription: "Verbindingsstuk voor de uitgang van de circulatiepomp. Via VanRobi.",
    image: withBase("/assets/products-catalog/aansluiting-pompuitgang.jpg"),
    alt: "Aansluiting pompuitgang, via VanRobi België & Nederland",
    cropClass: "crop-aansluiting-pompuitgang",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Plástico" }
    ],
  },
  {
    id: "startcondensator-roermotor",
    index: "77",
    name: "Startcondensator roermotor",
    badge: "Onderdelen · Elektrisch",
    description: "Startcondensator voor roermotor/agitator.",
    longDescription: "Startcondensator voor roermotoren (agitadores). Passend bij G8/G98-serie. Via VanRobi.",
    image: withBase("/assets/products-catalog/startcondensator-roermotor.jpg"),
    alt: "Startcondensator roermotor, via VanRobi België & Nederland",
    cropClass: "crop-startcondensator-roermotor",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Amplia gama de modelos" }
    ],
  },
  {
    id: "buisuiteinden",
    index: "78",
    name: "Buisuiteinden",
    badge: "Onderdelen · Leiding",
    description: "Eindstukken/conteras voor buizen.",
    longDescription: "Buisuiteinden (conteras) voor nette afwerking van leidingen. Via VanRobi.",
    image: withBase("/assets/products-catalog/buisuiteinden.jpg"),
    alt: "Buisuiteinden, via VanRobi België & Nederland",
    cropClass: "crop-buisuiteinden",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Plástico – ABS Color negro Color plata – cromadas" }
    ],
  },
  {
    id: "pvc-cristal-slang",
    index: "79",
    name: "PVC cristal slang",
    badge: "Onderdelen · Slang",
    description: "Transparante PVC cristal slang.",
    longDescription: "PVC cristal slang voor zichtbare of tijdelijke leidingen. Via VanRobi.",
    image: withBase("/assets/products-catalog/pvc-cristal-slang.jpg"),
    alt: "PVC cristal slang, via VanRobi België & Nederland",
    cropClass: "crop-pvc-cristal-slang",
    uses: ["horeca", "events"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Varias medidas", value: "Tubo pvc cristal 6 x 9 mm Tubo pvc cristal 7 x 10 mm" }
    ],
  },
  {
    id: "isolatieslang",
    index: "80",
    name: "Isolatieslang (coquilla)",
    badge: "Onderdelen · Isolatie",
    description: "Isolatieslang voor koude leidingen.",
    longDescription: "Isolatieslang (coquilla) tegen condens en warmte-inlek op koude leidingen. Via VanRobi.",
    image: withBase("/assets/products-catalog/isolatieslang.jpg"),
    alt: "Isolatieslang (coquilla), via VanRobi België & Nederland",
    cropClass: "crop-isolatieslang",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Varias medidas", value: "Tubo aislante 6 x 10 mm Tubo aislante 6 x 12 mm" }
    ],
  },
  {
    id: "pootdoppen",
    index: "81",
    name: "Pootdoppen",
    badge: "Onderdelen · Frame",
    description: "Doppen voor machinepoten.",
    longDescription: "Pootdoppen (conteras pata) voor stabiele plaatsing van units. Via VanRobi.",
    image: withBase("/assets/products-catalog/pootdoppen.jpg"),
    alt: "Pootdoppen, via VanRobi België & Nederland",
    cropClass: "crop-pootdoppen",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Plástico – ABS Color blanco Color negro" }
    ],
  },
  {
    id: "irrigatieslang-contact",
    index: "82",
    name: "Irrigatieslang contact",
    badge: "Onderdelen · Irrigatie",
    description: "Irrigatieslang voor contactkoeling in de ijsbank.",
    longDescription: "Irrigatieslang contact voor ijsbankcirculatie. Onderdeel van het roermotor-systeem. Via VanRobi.",
    image: withBase("/assets/products-catalog/irrigatieslang-contact.jpg"),
    alt: "Irrigatieslang contact, via VanRobi België & Nederland",
    cropClass: "crop-irrigatieslang-contact",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Merk", value: "VanRobi · BE & NL" },
      { label: "Leverancier", value: "VanRobi · België & Nederland" }
    ],
  },
  {
    id: "irrigatieslang-overstroming",
    index: "83",
    name: "Irrigatieslang overstroming",
    badge: "Onderdelen · Irrigatie",
    description: "Irrigatieslang voor overstromingskoeling.",
    longDescription: "Irrigatieslang overstroming voor ijsbankvulling/circulatie. Via VanRobi.",
    image: withBase("/assets/products-catalog/irrigatieslang-overstroming.jpg"),
    alt: "Irrigatieslang overstroming, via VanRobi België & Nederland",
    cropClass: "crop-irrigatieslang-overstroming",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Merk", value: "VanRobi · BE & NL" },
      { label: "Leverancier", value: "VanRobi · België & Nederland" }
    ],
  },
  {
    id: "versterkte-co2-slang",
    index: "84",
    name: "Versterkte CO₂-slang",
    badge: "Onderdelen · CO₂",
    description: "Versterkte slang voor CO₂.",
    longDescription: "Versterkte CO₂-slang voor veilige gastoevoer naar drukregelaars. Via VanRobi.",
    image: withBase("/assets/products-catalog/versterkte-co2-slang.jpg"),
    alt: "Versterkte CO₂-slang, via VanRobi België & Nederland",
    cropClass: "crop-versterkte-co2-slang",
    uses: ["horeca", "events"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Merk", value: "VanRobi · BE & NL" },
      { label: "Leverancier", value: "VanRobi · België & Nederland" }
    ],
  },
  {
    id: "afvoerslang",
    index: "85",
    name: "Afvoerslang",
    badge: "Onderdelen · Afvoer",
    description: "Afvoerslang voor condens/drainage.",
    longDescription: "Afvoerslang (desagüe) voor condenswater en drainage van koelers. Via VanRobi.",
    image: withBase("/assets/products-catalog/afvoerslang.jpg"),
    alt: "Afvoerslang, via VanRobi België & Nederland",
    cropClass: "crop-afvoerslang",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Merk", value: "VanRobi · BE & NL" },
      { label: "Leverancier", value: "VanRobi · België & Nederland" }
    ],
  },
  {
    id: "neopreen-isolatieplaat",
    index: "86",
    name: "Neopreen isolatieplaat",
    badge: "Onderdelen · Isolatie",
    description: "Neopreen isolatieplaat voor koude zones.",
    longDescription: "Neopreen isolatieplaat tegen condens en warmteverlies. Via VanRobi.",
    image: withBase("/assets/products-catalog/neopreen-isolatieplaat.jpg"),
    alt: "Neopreen isolatieplaat, via VanRobi België & Nederland",
    cropClass: "crop-neopreen-isolatieplaat",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Merk", value: "VanRobi · BE & NL" },
      { label: "Leverancier", value: "VanRobi · België & Nederland" }
    ],
  },
  {
    id: "reinigingsvloeistof-serpentijn",
    index: "87",
    name: "Reinigingsvloeistof serpentijn/kraan",
    badge: "Onderdelen · Reiniging",
    description: "Reinigingsvloeistof voor serpentijn- en kraancircuit.",
    longDescription: "Reinigingsvloeistof voor serpentijnen en kranen. Houdt de taplijn hygiënisch. Via VanRobi.",
    image: withBase("/assets/products-catalog/reinigingsvloeistof-serpentijn.jpg"),
    alt: "Reinigingsvloeistof serpentijn/kraan, via VanRobi België & Nederland",
    cropClass: "crop-reinigingsvloeistof-serpentijn",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Botella de 50 litros" }
    ],
  },
  {
    id: "reinigingstanks",
    index: "88",
    name: "Reinigingstanks",
    badge: "Onderdelen · Reiniging",
    description: "Tanks voor circuitreiniging van taplijnen.",
    longDescription: "Reinigingstanks (tanquetas) voor doorspoelen van serpentijnen en leidingen. Via VanRobi.",
    image: withBase("/assets/products-catalog/reinigingstanks.jpg"),
    alt: "Reinigingstanks, via VanRobi België & Nederland",
    cropClass: "crop-reinigingstanks",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "9 Litros – 18 Litros" },
      { label: "Info", value: "1- 4 bocas de limpieza" }
    ],
  },
  {
    id: "project-op-maat",
    index: "89",
    name: "Project op maat",
    badge: "Service · Project",
    description: "Speciale koel- en tapprojecten op maat.",
    longDescription: "Projecten op maat: speciale volumes, layouts of industriële toepassingen. VanRobi ontwerpt mee vanuit BE & NL.",
    image: withBase("/assets/products-catalog/project-op-maat.jpg"),
    alt: "Project op maat, via VanRobi België & Nederland",
    cropClass: "crop-project-op-maat",
    uses: ["horeca", "events"],
    group: "service",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "¡Consúltanos!" }
    ],
  },
  {
    id: "reparatie-koelers",
    index: "90",
    name: "Reparatie koelers",
    badge: "Service · Reparatie",
    description: "Reparatie van ijsbankkoelers en enfriadores.",
    longDescription: "Reparatie van ijsbankkoelers: diagnose, onderdelen en herstel. Via VanRobi en partner Taponderhoud in België & Nederland.",
    image: withBase("/assets/products-catalog/reparatie-koelers.jpg"),
    alt: "Reparatie koelers, via VanRobi België & Nederland",
    cropClass: "crop-reparatie-koelers",
    uses: ["horeca"],
    group: "service",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Limpieza" },
      { label: "Info", value: "Sustitución de piezas" }
    ],
  },
  {
    id: "reparatie-roermotoren",
    index: "91",
    name: "Reparatie roermotoren",
    badge: "Service · Reparatie",
    description: "Reparatie van roermotoren/agitadores.",
    longDescription: "Reparatie van roermotoren (G8/G98 e.d.). Snel weer circulatie in de ijsbank. Via VanRobi.",
    image: withBase("/assets/products-catalog/reparatie-roermotoren.jpg"),
    alt: "Reparatie roermotoren, via VanRobi België & Nederland",
    cropClass: "crop-reparatie-roermotoren",
    uses: ["horeca"],
    group: "service",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Limpieza" },
      { label: "Info", value: "Sustitución de piezas" }
    ],
  },
  {
    id: "reparatie-kranen",
    index: "92",
    name: "Reparatie kranen",
    badge: "Service · Reparatie",
    description: "Reparatie en revisie van tapkranen.",
    longDescription: "Reparatie van tapkranen: lekkage, slijtage, revisie. Via VanRobi / Taponderhoud.",
    image: withBase("/assets/products-catalog/reparatie-kranen.jpg"),
    alt: "Reparatie kranen, via VanRobi België & Nederland",
    cropClass: "crop-reparatie-kranen",
    uses: ["horeca"],
    group: "service",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Limpieza" },
      { label: "Info", value: "Sustitución de piezas" }
    ],
  },
  {
    id: "bedieningspaneel",
    index: "93",
    name: "Bedieningspaneel",
    badge: "Onderdelen · Besturing",
    description: "Bedienings-/schakelpaneel voor koelinstallaties.",
    longDescription: "Paneel de maniobra: schakel- en bedieningspaneel voor koel- en pompinstallaties. Via VanRobi.",
    image: withBase("/assets/products-catalog/bedieningspaneel.jpg"),
    alt: "Bedieningspaneel, via VanRobi België & Nederland",
    cropClass: "crop-bedieningspaneel",
    uses: ["horeca"],
    group: "onderdelen",
    featured: false,
    imageKind: "photo",
    specs: [
      { label: "Info", value: "Panel manorreductores" },
      { label: "Info", value: "Panel bocas limpieza" },
      { label: "Info", value: "Panel otros componentes" }
    ],
  },
];

