/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DienstenRouteImport } from './routes/diensten'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as RegioRouteImport } from './routes/regio'
import { Route as VergelijkRouteImport } from './routes/vergelijk'
import { Route as VoorWieRouteImport } from './routes/voor-wie'
import { Route as FrIndexRouteImport } from './routes/fr/index'
import { Route as FrAProposRouteImport } from './routes/fr/a-propos'
import { Route as FrContactRouteImport } from './routes/fr/contact'
import { Route as FrFaqRouteImport } from './routes/fr/faq'
import { Route as FrServicesRouteImport } from './routes/fr/services'
import { Route as GidsIndexRouteImport } from './routes/gids/index'
import { Route as GidsSlugRouteImport } from './routes/gids/$slug'
import { Route as ProductenIndexRouteImport } from './routes/producten/index'
import { Route as ProductenIdRouteImport } from './routes/producten/$id'
import { Route as FrProduitsIndexRouteImport } from './routes/fr/produits/index'
import { Route as FrProduitsIdRouteImport } from './routes/fr/produits/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstenRoute = DienstenRouteImport.update({
  id: '/diensten',
  path: '/diensten',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const RegioRoute = RegioRouteImport.update({
  id: '/regio',
  path: '/regio',
  getParentRoute: () => rootRouteImport,
} as any)
const VergelijkRoute = VergelijkRouteImport.update({
  id: '/vergelijk',
  path: '/vergelijk',
  getParentRoute: () => rootRouteImport,
} as any)
const VoorWieRoute = VoorWieRouteImport.update({
  id: '/voor-wie',
  path: '/voor-wie',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/fr/',
  path: '/fr/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrAProposRoute = FrAProposRouteImport.update({
  id: '/fr/a-propos',
  path: '/fr/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const FrContactRoute = FrContactRouteImport.update({
  id: '/fr/contact',
  path: '/fr/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FrFaqRoute = FrFaqRouteImport.update({
  id: '/fr/faq',
  path: '/fr/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FrServicesRoute = FrServicesRouteImport.update({
  id: '/fr/services',
  path: '/fr/services',
  getParentRoute: () => rootRouteImport,
} as any)
const GidsIndexRoute = GidsIndexRouteImport.update({
  id: '/gids/',
  path: '/gids/',
  getParentRoute: () => rootRouteImport,
} as any)
const GidsSlugRoute = GidsSlugRouteImport.update({
  id: '/gids/$slug',
  path: '/gids/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductenIndexRoute = ProductenIndexRouteImport.update({
  id: '/producten/',
  path: '/producten/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductenIdRoute = ProductenIdRouteImport.update({
  id: '/producten/$id',
  path: '/producten/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FrProduitsIndexRoute = FrProduitsIndexRouteImport.update({
  id: '/fr/produits/',
  path: '/fr/produits/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrProduitsIdRoute = FrProduitsIdRouteImport.update({
  id: '/fr/produits/$id',
  path: '/fr/produits/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/faq': typeof FaqRoute
  '/over-ons': typeof OverOnsRoute
  '/regio': typeof RegioRoute
  '/vergelijk': typeof VergelijkRoute
  '/voor-wie': typeof VoorWieRoute
  '/fr/a-propos': typeof FrAProposRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/faq': typeof FrFaqRoute
  '/fr/services': typeof FrServicesRoute
  '/gids/$slug': typeof GidsSlugRoute
  '/producten/$id': typeof ProductenIdRoute
  '/fr/': typeof FrIndexRoute
  '/gids/': typeof GidsIndexRoute
  '/producten/': typeof ProductenIndexRoute
  '/fr/produits/$id': typeof FrProduitsIdRoute
  '/fr/produits/': typeof FrProduitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/faq': typeof FaqRoute
  '/over-ons': typeof OverOnsRoute
  '/regio': typeof RegioRoute
  '/vergelijk': typeof VergelijkRoute
  '/voor-wie': typeof VoorWieRoute
  '/fr/a-propos': typeof FrAProposRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/faq': typeof FrFaqRoute
  '/fr/services': typeof FrServicesRoute
  '/gids/$slug': typeof GidsSlugRoute
  '/producten/$id': typeof ProductenIdRoute
  '/fr': typeof FrIndexRoute
  '/gids': typeof GidsIndexRoute
  '/producten': typeof ProductenIndexRoute
  '/fr/produits/$id': typeof FrProduitsIdRoute
  '/fr/produits': typeof FrProduitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/faq': typeof FaqRoute
  '/over-ons': typeof OverOnsRoute
  '/regio': typeof RegioRoute
  '/vergelijk': typeof VergelijkRoute
  '/voor-wie': typeof VoorWieRoute
  '/fr/a-propos': typeof FrAProposRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/faq': typeof FrFaqRoute
  '/fr/services': typeof FrServicesRoute
  '/gids/$slug': typeof GidsSlugRoute
  '/producten/$id': typeof ProductenIdRoute
  '/fr/': typeof FrIndexRoute
  '/gids/': typeof GidsIndexRoute
  '/producten/': typeof ProductenIndexRoute
  '/fr/produits/$id': typeof FrProduitsIdRoute
  '/fr/produits/': typeof FrProduitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/diensten'
    | '/faq'
    | '/over-ons'
    | '/regio'
    | '/vergelijk'
    | '/voor-wie'
    | '/fr/a-propos'
    | '/fr/contact'
    | '/fr/faq'
    | '/fr/services'
    | '/gids/$slug'
    | '/producten/$id'
    | '/fr/'
    | '/gids/'
    | '/producten/'
    | '/fr/produits/$id'
    | '/fr/produits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/diensten'
    | '/faq'
    | '/over-ons'
    | '/regio'
    | '/vergelijk'
    | '/voor-wie'
    | '/fr/a-propos'
    | '/fr/contact'
    | '/fr/faq'
    | '/fr/services'
    | '/gids/$slug'
    | '/producten/$id'
    | '/fr'
    | '/gids'
    | '/producten'
    | '/fr/produits/$id'
    | '/fr/produits'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/diensten'
    | '/faq'
    | '/over-ons'
    | '/regio'
    | '/vergelijk'
    | '/voor-wie'
    | '/fr/a-propos'
    | '/fr/contact'
    | '/fr/faq'
    | '/fr/services'
    | '/gids/$slug'
    | '/producten/$id'
    | '/fr/'
    | '/gids/'
    | '/producten/'
    | '/fr/produits/$id'
    | '/fr/produits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DienstenRoute: typeof DienstenRoute
  FaqRoute: typeof FaqRoute
  OverOnsRoute: typeof OverOnsRoute
  RegioRoute: typeof RegioRoute
  VergelijkRoute: typeof VergelijkRoute
  VoorWieRoute: typeof VoorWieRoute
  FrAProposRoute: typeof FrAProposRoute
  FrContactRoute: typeof FrContactRoute
  FrFaqRoute: typeof FrFaqRoute
  FrServicesRoute: typeof FrServicesRoute
  GidsSlugRoute: typeof GidsSlugRoute
  ProductenIdRoute: typeof ProductenIdRoute
  FrIndexRoute: typeof FrIndexRoute
  GidsIndexRoute: typeof GidsIndexRoute
  ProductenIndexRoute: typeof ProductenIndexRoute
  FrProduitsIdRoute: typeof FrProduitsIdRoute
  FrProduitsIndexRoute: typeof FrProduitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten': {
      id: '/diensten'
      path: '/diensten'
      fullPath: '/diensten'
      preLoaderRoute: typeof DienstenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regio': {
      id: '/regio'
      path: '/regio'
      fullPath: '/regio'
      preLoaderRoute: typeof RegioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vergelijk': {
      id: '/vergelijk'
      path: '/vergelijk'
      fullPath: '/vergelijk'
      preLoaderRoute: typeof VergelijkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voor-wie': {
      id: '/voor-wie'
      path: '/voor-wie'
      fullPath: '/voor-wie'
      preLoaderRoute: typeof VoorWieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/': {
      id: '/fr/'
      path: '/fr'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/a-propos': {
      id: '/fr/a-propos'
      path: '/fr/a-propos'
      fullPath: '/fr/a-propos'
      preLoaderRoute: typeof FrAProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/contact': {
      id: '/fr/contact'
      path: '/fr/contact'
      fullPath: '/fr/contact'
      preLoaderRoute: typeof FrContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/faq': {
      id: '/fr/faq'
      path: '/fr/faq'
      fullPath: '/fr/faq'
      preLoaderRoute: typeof FrFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/services': {
      id: '/fr/services'
      path: '/fr/services'
      fullPath: '/fr/services'
      preLoaderRoute: typeof FrServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gids/': {
      id: '/gids/'
      path: '/gids'
      fullPath: '/gids/'
      preLoaderRoute: typeof GidsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gids/$slug': {
      id: '/gids/$slug'
      path: '/gids/$slug'
      fullPath: '/gids/$slug'
      preLoaderRoute: typeof GidsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producten/': {
      id: '/producten/'
      path: '/producten'
      fullPath: '/producten/'
      preLoaderRoute: typeof ProductenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producten/$id': {
      id: '/producten/$id'
      path: '/producten/$id'
      fullPath: '/producten/$id'
      preLoaderRoute: typeof ProductenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/produits/': {
      id: '/fr/produits/'
      path: '/fr/produits'
      fullPath: '/fr/produits/'
      preLoaderRoute: typeof FrProduitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/produits/$id': {
      id: '/fr/produits/$id'
      path: '/fr/produits/$id'
      fullPath: '/fr/produits/$id'
      preLoaderRoute: typeof FrProduitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DienstenRoute: DienstenRoute,
  FaqRoute: FaqRoute,
  OverOnsRoute: OverOnsRoute,
  RegioRoute: RegioRoute,
  VergelijkRoute: VergelijkRoute,
  VoorWieRoute: VoorWieRoute,
  FrAProposRoute: FrAProposRoute,
  FrContactRoute: FrContactRoute,
  FrFaqRoute: FrFaqRoute,
  FrServicesRoute: FrServicesRoute,
  GidsSlugRoute: GidsSlugRoute,
  ProductenIdRoute: ProductenIdRoute,
  FrIndexRoute: FrIndexRoute,
  GidsIndexRoute: GidsIndexRoute,
  ProductenIndexRoute: ProductenIndexRoute,
  FrProduitsIdRoute: FrProduitsIdRoute,
  FrProduitsIndexRoute: FrProduitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
